// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/jmoiron/sqlx"
	"github.com/user/simple-blog/config"
	handler2 "github.com/user/simple-blog/internal/modules/auth/handler"
	repository2 "github.com/user/simple-blog/internal/modules/auth/repository"
	service2 "github.com/user/simple-blog/internal/modules/auth/service"
	handler4 "github.com/user/simple-blog/internal/modules/comments/handler"
	repository4 "github.com/user/simple-blog/internal/modules/comments/repository"
	service4 "github.com/user/simple-blog/internal/modules/comments/service"
	"github.com/user/simple-blog/internal/modules/health/handler"
	"github.com/user/simple-blog/internal/modules/health/repository"
	"github.com/user/simple-blog/internal/modules/health/service"
	handler3 "github.com/user/simple-blog/internal/modules/posts/handler"
	repository3 "github.com/user/simple-blog/internal/modules/posts/repository"
	service3 "github.com/user/simple-blog/internal/modules/posts/service"
	"github.com/user/simple-blog/internal/platform/database"
	"github.com/user/simple-blog/internal/platform/server"
)

// Injectors from wire.go:

func InitializeServer(cfg *config.Config, db *sqlx.DB) *server.Server {
	healthRepository := repository.NewHealthRepository(db)
	healthService := service.NewHealthService(healthRepository)
	healthHandler := handler.NewHealthHandler(healthService)
	authRepository := repository2.NewAuthRepository(db)
	transactor := database.NewTransactor(db)
	authService := service2.NewAuthService(authRepository, cfg, transactor)
	authHandler := handler2.NewAuthHandler(authService)
	postRepository := repository3.NewPostRepository(db)
	postService := service3.NewPostService(postRepository, transactor)
	postHandler := handler3.NewPostHandler(postService)
	commentRepository := repository4.NewCommentRepository(db)
	commentService := service4.NewCommentService(commentRepository, postService)
	commentHandler := handler4.NewCommentHandler(commentService)
	serverServer := server.NewServer(cfg, db, healthHandler, authHandler, postHandler, commentHandler)
	return serverServer
}
