// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/jmoiron/sqlx"
	"github.com/user/go-backend-boilerplate/config"
	handler2 "github.com/user/go-backend-boilerplate/internal/modules/auth/handler"
	repository2 "github.com/user/go-backend-boilerplate/internal/modules/auth/repository"
	service2 "github.com/user/go-backend-boilerplate/internal/modules/auth/service"
	"github.com/user/go-backend-boilerplate/internal/modules/health/handler"
	"github.com/user/go-backend-boilerplate/internal/modules/health/repository"
	"github.com/user/go-backend-boilerplate/internal/modules/health/service"
	"github.com/user/go-backend-boilerplate/internal/platform/server"
)

// Injectors from wire.go:

func InitializeServer(cfg *config.Config, db *sqlx.DB) *server.Server {
	healthRepository := repository.NewHealthRepository(db)
	healthService := service.NewHealthService(healthRepository)
	healthHandler := handler.NewHealthHandler(healthService)
	authRepository := repository2.NewAuthRepository(db)
	authService := service2.NewAuthService(authRepository, cfg)
	authHandler := handler2.NewAuthHandler(authService)
	serverServer := server.NewServer(cfg, db, healthHandler, authHandler)
	return serverServer
}
