basePath: /
definitions:
  github_com_user_go-backend-boilerplate_internal_modules_health_domain.HealthResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@example.com
    name: API Support
  description: This is a sample blog system server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Blog System API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Get the status of the service and database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_user_go-backend-boilerplate_internal_modules_health_domain.HealthResponse'
      summary: Check service health
      tags:
      - Health
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
